# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:  # Not a client, don't register with yourself
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  server:
    eviction-interval-timer-in-ms: 1000

server:
  port: 5555   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf
  application:
    name: eureka  # Identify this application